### PR TITLE
Release/0.2.2

### PR DESCRIPTION
**Pull request by colmsnowplow**

### CODE REVIEW

**Review by paulboocock — APPROVED** [review]
LGTM

**Comment by paulboocock** [comment]
Should the vendor folder have been deleted too, rather than just excluded?

**Comment by colmsnowplow** [comment]
@paulboocock yup, I had removed them but in the same commit as adding to gitignore, which undid it 🤦  - fixed with rebase now. :)

**Review by paulboocock — APPROVED** [review]
LGTM.

Out of scope for 0.2.2 but it would be good to do a 0.2.3 with Snyk scanning in to. This is used in production now and doesn't have automated Snyk scanning on release.

**Comment by colmsnowplow** [comment]
> Out of scope for 0.2.2 but it would be good to do a 0.2.3 with Snyk scanning in to. This is used in production now and doesn't have automated Snyk scanning on release.

Good shout, I hadn't realised it's not on here. We have a 0.2.3 bugfix release coming so we can get it into that one.

**Pull request merged**
