### PR TITLE
Add Snyk scanning (closes #25)

### LINKED ISSUE #25: Add Snyk scanning
We should be scanning this repository with Snyk just like we do with all our other repositories.

e.g..
https://github.com/snowplow/sql-runner/blob/master/.github/workflows/snyk.yml

### PR DESCRIPTION
**Pull request by TiganeteaRobert**

### CODE REVIEW

**Comment by colmsnowplow** [comment]
@paulboocock could you please add a SNYK_TOKEN cred to this repo?

@TiganeteaRobert once that's done, let's give this a test by committing a change to the config to enable it for branches, then once it's run successfully, we can rebase that change out. I'd like to avoid needing to debug after merge to master.

Would be great if you could pop a link to a successful run in here.

**Comment by paulboocock** [comment]
SNYK_TOKEN has been added.

**Comment by TiganeteaRobert** [comment]
https://app.snyk.io/org/data-value/project/dd9fc463-3f15-493d-ba1c-cbb97c242bce/history/4896eebd-5e0a-41e5-9d76-cdf60ddf54fb

Snyk snapshot here!

**Review by colmsnowplow — APPROVED** [review]
LGTM!

**Pull request merged**
